# Generated by Django 5.2.1 on 2025-05-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='department',
            field=models.CharField(default='development', max_length=50),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
    ]
