# Generated by Django 5.2.1 on 2025-05-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_teammember_experience_project_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('source', models.CharField(default='website', help_text='Source of the contact form (website, chatbot, etc.)', max_length=50)),
            ],
            options={
                'ordering': ['-date_submitted'],
            },
        ),
    ]
