# Generated by Django 5.0.2 on 2025-07-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickReplyTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for this template', max_length=100)),
                ('template_type', models.CharField(choices=[('general', 'General Inquiry'), ('reseller', 'Reseller Information'), ('support', 'Support Request'), ('custom', 'Custom Template')], default='general', max_length=20)),
                ('subject', models.CharField(help_text='Email subject line', max_length=200)),
                ('message', models.TextField(help_text="Email message content. You can use {name} to insert recipient's name.")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_type', 'name'],
            },
        ),
    ]
